### ISSUE TITLE
Bug Report: How To Play Fnf 0.4.1 On Android

### ISSUE THREAD

**Issue by Klaskycs** [MAJigsaw77/Funkin#18] opened 2024-06-22 00:22 UTC
HOW TO PLAY FNF 0.4.1 ON ANDROID 
I CAN'T PLAY FNF 0.4.1 ON MY PHONE BECAUSE OF REMOVING OPEN BUTTON

**Comment by moondroidcoder** [comment] 2024-06-22 00:26
Can you please talk normally we geneuinely do not understand you

**Comment by Vini158916** [comment] 2024-06-22 00:26
The apk is bugged, everyone is having this problem, but I think they will fix that soon

**Comment by ghost** [comment] 2024-06-22 00:29
*sigh* duplicate of #16

**Closed as completed by ghost** 2024-06-22 00:29 UTC
Labels: bug
