### ISSUE TITLE
Crash after 2hot to blazin'  cutscene

### ISSUE THREAD

**Issue by Gustsonic1682** [MAJigsaw77/Funkin#33] opened 2024-09-22 02:14 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 (i ve  seen the compilation from sector)

### Context (Provide screenshots or videos of the crash happening)

Crash in cutscene after 2hot :/ 

### Steps to reproduce

Play WeekEnd 1
After Finishing 2hot cutscene 
The game crash

### Crash logs (can be found in the logs folder where Funkin.exe is)

Null Object Reference
  in flixel/addons/display/FlxTiledSprite.hx#225
  in flixel/addons/display/FlxTiledSprite.hx#137
  in flixel/addons/display/FlxTiledSprite.hx#146
  in flixel/group/FlxGroup.hx#180
  in flixel/group/FlxSpriteGroup.hx#233
  in funkin/play/stage/Stage.hx#810
  in polymod/hscript/_internal/HScriptedClassMacro.hx#870
  in /opt/hostedtoolcache/haxe/4.3.6/x64/std/cpp/_std/Reflect.hx#63
  in polymod/hscript/_internal/PolymodScriptClass.hx#553
  in polymod/hscript/_internal/HScriptedClassMacro.hx#837
  in flixel/group/FlxGroup.hx#180
  in flixel/FlxState.hx#109
  in flixel/FlxSubState.hx#80
  in funkin/play/PlayState.hx#811
  in flixel/FlxGame.hx#882
  in flixel/FlxGame.hx#567

**Comment by Gustsonic1682** [comment] 2024-09-22 02:14
Even If you Skip the game crash

**Comment by KarimAkra** [comment] 2024-09-22 11:19
Duplicate of #31

**Closed as completed by KarimAkra** 2024-09-22 11:19 UTC
