### ISSUE TITLE
Bug Report: 120hz (ProMotion) not properly working on iOS

### ISSUE THREAD

**Issue by dotevie** [MAJigsaw77/Funkin#20] opened 2024-06-22 05:32 UTC
## Describe the bug
On a ProMotion iOS device, the game is artificially capped to 60 FPS, causing all animations and tweens to run at half speed, since it's expecting 120 FPS.

## To Reproduce

1. Open the game on a ProMotion device (iPhone 13 Pro or above, iPad Pro)
## Expected behavior
The game runs at or near 120 FPS

## Desktop
 - OS: iOS 18.0
 
 - Browser: N/A
 
 - Version: 0.4.1
 

## Additional context
I'm not sure how this is intended to work, seeming as ProMotion seems to be relatively undocumented behaviour when it comes to Lime, but if needed I'm willing to help figure it out

**Comment by MAJigsaw77** [comment] 2024-06-22 05:59
By taking a look at this it seems that your display is not set to 120 fps https://github.com/FunkinDroidTeam/Funkin/blob/c4f4e2d1868d4f718b114df4a20a0c263d1fc2c4/source/Main.hx#L129

**Comment by moondroidcoder** [comment] 2024-06-23 11:31
Closing as it seems to work as intended

**Closed as completed by moondroidcoder** 2024-06-23 11:31 UTC
Labels: bug
