### ISSUE TITLE
Crash Report: Still crashes when getting to 2hot in WeekEnd1

### ISSUE THREAD

**Issue by whateverlior** [MAJigsaw77/Funkin#34] opened 2024-09-23 20:28 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

So I know it has been like this recently. and I got the newest 0.5.0 from the actions, but the problem still occurs. is there a quick solution?

### Steps to reproduce

Play Weekend1
get through the first 3 songs
kaboom, crash

### Crash logs (can be found in the logs folder where Funkin.exe is)

Everyone already knows it's a Null Object Reference problem, whatever that is

**Comment by sector-a** [comment] 2024-09-23 21:17
duplicate of #27
we know already about this issue.
thank you for reminding us:)

**Closed as completed** 2024-09-23 21:18 UTC
