### ISSUE TITLE
App cannot be opened when installed - Version 0.4.1

### ISSUE THREAD

**Issue by Vini158916** [MAJigsaw77/Funkin#17] opened 2024-06-22 00:09 UTC
Device: Samsung Galaxy S20 FE 5G

1. Steps to reproduce,
2. What you expected to see, and
3. What you saw instead."

-->
1. Open downloaded apk and install it.
2. App installed for playing
3. Play Protect warning, but ignored it. The app installed, but can't open it

## Describe the bug

- Basically, the apk install normally, but when I try to open... IT CANNOT BE OPENED.

## To Reproduce
 Download apk, open downloaded file, install apk, play protect warning appears (but I install as same), app cannot be opened.
## Expected Behiavor.
 Apk install normally and play it

## Screenshots/Video
 Sorry but I cant take screenshots (it's not my phone, but I'm from another country and language is different)

## Desktop
 - OS:
  Android 13
 - Browser
  Opera (Normal, not GX)
 - Version:
  0.4.1

## Additional context
 Before this port released, I used a 0.4.0 port that I found, and when this error will not be fixed I will use the port I found. But when this gonna be fixed, I will use this port

 I don't play on web version

**Comment by ghost** [comment] 2024-06-22 00:12
duplicate of #16

**Closed as completed by ghost** 2024-06-22 00:12 UTC
Labels: bug
